# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49843aea78feb0e7281504ef27de02569b5d13df064113b442d70029a11a633c7cd05ec9333c060f81e0f181f925e33a275efdb709a474bdc20d08ed5e221275

test:
  secret_key_base: 9bd4b756ea4be28443aefe1edc63ff2b6e0826ff3b3f925945c7ec1e217437ef8bb6489343635728b2c4df1e3c683133fcf421ab0fc062696d06d3d73b3b1410

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
